"""
 try catch example

 Author: Irwin Rodr√≠guez <rodriguez.irwin@gmail.com>
 Date: 2023-02-26
"""

def fTest
    try        
        let nA = 10, nB = 20
        nC = nA + nB # nC is not defined
        return "try"
    catch
        pPrintLn("ERROR MESSAGE: " & oEx.message)
    finally
        pPrintLn("finally block should be used to close resources")
    end
    return "end"
end

pPrintLn(fTest())